version: "1"

services:
  server:
    build: ./
    ports:
      - "8888:8888"
    depends_on:
      - db
    
  client:
  build: ./
  ports:
    - "3000:3000"
  
  db:
    image: mongo
    ports:
      - "27017:27017"
    